#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Oct 31 18:41:30 MSK 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=15
shaderPack=ComplementaryReimagined_r5.5.1.zip
